# rubocop:disable all

# Uninstall everything but this file:
# brew bundle cleanup --force 

brew 'awscli'
brew 'bash'
brew 'bat'
brew 'colima'
brew 'curl'
brew 'diff-so-fancy'
brew 'docker'
brew 'docker-compose'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'glow'
brew 'htop'
brew 'jq'
brew 'kubectl'
brew 'kubectx'
brew 'mise'
brew 'ncdu'
# Use mise untill 0.12 release
# brew 'neovim' 
brew 'nmap'
brew 'openssh'
brew 'openssl'
brew 'ripgrep'
brew 'stow'
brew 'streamlink'
brew 'tig'
brew 'tldr'
brew 'tmux'
brew 'urlview'
brew 'wget'
brew 'zoxide'

cask 'alacritty'
cask 'alfred'
cask 'firefox'
cask 'discord'
cask 'drawio'
cask 'hammerspoon'
cask 'kap'
cask 'karabiner-elements'
cask 'keepassxc'
cask 'keycastr'
cask 'obsidian'
cask 'sdm'
cask 'slack'
cask 'spotify'
cask 'syncthing-app'
cask 'telegram'
cask 'the-unarchiver'
cask 'transmission'
cask 'vlc'
cask 'font-fira-code'
