tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "bash"
brew "bat"
brew "curl"
brew "diff-so-fancy"
brew "fd"
brew "fzf"
brew "git"
brew "htop"
brew "mysql", restart_service: true
brew "postgresql", restart_service: true
brew "redis", restart_service: true
brew "neovim"
brew "nmap"
brew "node"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "speedtest-cli"
brew "stow"
brew "tree"
brew "streamlink"
brew "tig"
brew "tldr"
brew "tmux"
brew "urlview"
brew "wget"

cask "alfred"
cask "dash"
cask "discord"
cask "iterm2"
cask "karabiner-elements"
cask "macdown"
cask "macvim"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "sequel-pro"
cask "steam"
cask "transmission"
cask "virtualbox"
cask "vlc"
cask "webpquicklook"
cask "xquartz"
