general {
    lock_cmd = 
    before_sleep_cmd = 
    after_sleep_cmd = 
    ignore_dbus_inhibit = false
}

# Sleep screens and turn off TV after 10 minutes of inactivity
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off && /home/madundead/.scripts/lgtv/off.sh
    on-resume = /home/madundead/.scripts/lgtv/on.sh & sleep 1 && hyprctl dispatch dpms on
}
